export  const ADD_FAV_POST_ITEM ="ADD_ORDER_ITEM";
export  const DELETE_FAV_POST_ITEM ="DELETE_ORDER_ITEM";

export  const UPDATE_TEMP_POST_ITEM ="DELETE_ORDER_ITEM";


export  const ALERT_SYSTEM_SHOW ="ALERT_SYSTEM_SHOW";
